package com.alibaba.nacos.proto.generator;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;

public class ProtoFileWriter {

    private static final Map<String, String> MODULE_PACKAGES = Map.of(
        "common", "nacos.common",
        "config", "nacos.config",
        "naming", "nacos.naming",
        "lock", "nacos.lock",
        "ai", "nacos.ai"
    );

    private static final Map<String, String> MODULE_GO_PACKAGES = Map.of(
        "common", "github.com/nacos-group/nacos-sdk-proto-go/common",
        "config", "github.com/nacos-group/nacos-sdk-proto-go/config",
        "naming", "github.com/nacos-group/nacos-sdk-proto-go/naming",
        "lock", "github.com/nacos-group/nacos-sdk-proto-go/lock",
        "ai", "github.com/nacos-group/nacos-sdk-proto-go/ai"
    );

    private final TypeMapper typeMapper = new TypeMapper();

    public void write(Path outputDir, Map<String, List<MessageDescriptor>> messagesByFile) throws IOException {
        for (var entry : messagesByFile.entrySet()) {
            String filePath = entry.getKey();
            List<MessageDescriptor> messages = entry.getValue();
            if (messages.isEmpty()) continue;

            String module = messages.get(0).module();
            Path outFile = outputDir.resolve(filePath);
            Files.createDirectories(outFile.getParent());

            StringBuilder sb = new StringBuilder();
            sb.append("// Auto-generated by proto-generator. DO NOT EDIT.\n");
            sb.append("syntax = \"proto3\";\n");
            sb.append("package ").append(MODULE_PACKAGES.getOrDefault(module, "nacos." + module)).append(";\n\n");
            sb.append("option go_package = \"")
              .append(MODULE_GO_PACKAGES.getOrDefault(module, "github.com/nacos-group/nacos-sdk-proto-go/" + module))
              .append("\";\n");

            Set<String> imports = collectImports(messages, module);
            if (!imports.isEmpty()) {
                sb.append("\n");
                for (String imp : imports) {
                    sb.append("import \"").append(imp).append("\";\n");
                }
            }

            for (MessageDescriptor msg : messages) {
                sb.append("\n");
                sb.append("// metadata.type = \"").append(msg.name()).append("\"\n");
                sb.append("// Flattened from: ").append(msg.inheritanceChain()).append("\n");
                sb.append("message ").append(msg.name()).append(" {\n");

                for (FieldInfo field : msg.fields()) {
                    String protoType = typeMapper.mapType(field.type(), field.genericType());
                    int number = msg.fieldNumbers().get(field.name());
                    sb.append("  ").append(protoType).append(" ").append(field.name())
                      .append(" = ").append(number).append(";\n");
                }

                if (!msg.reserved().isEmpty()) {
                    sb.append("  reserved ").append(
                        msg.reserved().stream().map(String::valueOf).collect(Collectors.joining(", "))
                    ).append(";\n");
                }

                sb.append("}\n");
            }

            Files.writeString(outFile, sb.toString());
        }
    }

    private Set<String> collectImports(List<MessageDescriptor> messages, String currentModule) {
        Set<String> imports = new TreeSet<>();
        for (MessageDescriptor msg : messages) {
            for (FieldInfo field : msg.fields()) {
                String protoType = typeMapper.mapType(field.type(), field.genericType());
                if (protoType.contains("google.protobuf.Value")) {
                    imports.add("google/protobuf/struct.proto");
                }
            }
        }
        return imports;
    }
}
