// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "ConnectionSetupRequest"
type ConnectionSetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ClientVersion string                 `protobuf:"bytes,2,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AbilityTable  map[string]bool        `protobuf:"bytes,5,rep,name=abilityTable,proto3" json:"abilityTable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionSetupRequest) Reset() {
	*x = ConnectionSetupRequest{}
	mi := &file_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionSetupRequest) ProtoMessage() {}

func (x *ConnectionSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionSetupRequest.ProtoReflect.Descriptor instead.
func (*ConnectionSetupRequest) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionSetupRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectionSetupRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ConnectionSetupRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConnectionSetupRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ConnectionSetupRequest) GetAbilityTable() map[string]bool {
	if x != nil {
		return x.AbilityTable
	}
	return nil
}

// metadata.type = "SetupAckRequest" (server -> client)
type SetupAckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	AbilityTable  map[string]bool        `protobuf:"bytes,2,rep,name=abilityTable,proto3" json:"abilityTable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupAckRequest) Reset() {
	*x = SetupAckRequest{}
	mi := &file_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupAckRequest) ProtoMessage() {}

func (x *SetupAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupAckRequest.ProtoReflect.Descriptor instead.
func (*SetupAckRequest) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *SetupAckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SetupAckRequest) GetAbilityTable() map[string]bool {
	if x != nil {
		return x.AbilityTable
	}
	return nil
}

// metadata.type = "SetupAckResponse" (client -> server)
type SetupAckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupAckResponse) Reset() {
	*x = SetupAckResponse{}
	mi := &file_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupAckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupAckResponse) ProtoMessage() {}

func (x *SetupAckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupAckResponse.ProtoReflect.Descriptor instead.
func (*SetupAckResponse) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *SetupAckResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SetupAckResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SetupAckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetupAckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConnectResetRequest" (server -> client)
type ConnectResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ServerIp      string                 `protobuf:"bytes,2,opt,name=serverIp,proto3" json:"serverIp,omitempty"`
	ServerPort    string                 `protobuf:"bytes,3,opt,name=serverPort,proto3" json:"serverPort,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,4,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResetRequest) Reset() {
	*x = ConnectResetRequest{}
	mi := &file_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResetRequest) ProtoMessage() {}

func (x *ConnectResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResetRequest.ProtoReflect.Descriptor instead.
func (*ConnectResetRequest) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConnectResetRequest) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

func (x *ConnectResetRequest) GetServerPort() string {
	if x != nil {
		return x.ServerPort
	}
	return ""
}

func (x *ConnectResetRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// metadata.type = "ServerCheckRequest"
type ServerCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCheckRequest) Reset() {
	*x = ServerCheckRequest{}
	mi := &file_common_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckRequest) ProtoMessage() {}

func (x *ServerCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCheckRequest.ProtoReflect.Descriptor instead.
func (*ServerCheckRequest) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{4}
}

func (x *ServerCheckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ServerCheckResponse"
type ServerCheckResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ResultCode                int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode                 int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message                   string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId                 string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ConnectionId              string                 `protobuf:"bytes,5,opt,name=connectionId,proto3" json:"connectionId,omitempty"`
	SupportAbilityNegotiation bool                   `protobuf:"varint,6,opt,name=supportAbilityNegotiation,proto3" json:"supportAbilityNegotiation,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ServerCheckResponse) Reset() {
	*x = ServerCheckResponse{}
	mi := &file_common_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCheckResponse) ProtoMessage() {}

func (x *ServerCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCheckResponse.ProtoReflect.Descriptor instead.
func (*ServerCheckResponse) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{5}
}

func (x *ServerCheckResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ServerCheckResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ServerCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerCheckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerCheckResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ServerCheckResponse) GetSupportAbilityNegotiation() bool {
	if x != nil {
		return x.SupportAbilityNegotiation
	}
	return false
}

// metadata.type = "HealthCheckRequest"
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_common_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "HealthCheckResponse"
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_common_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *HealthCheckResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ErrorResponse"
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_common_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ErrorResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_common_common_proto protoreflect.FileDescriptor

const file_common_common_proto_rawDesc = "" +
	"\n" +
	"\x13common/common.proto\x12\fnacos.common\"\x96\x03\n" +
	"\x16ConnectionSetupRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12$\n" +
	"\rclientVersion\x18\x02 \x01(\tR\rclientVersion\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12H\n" +
	"\x06labels\x18\x04 \x03(\v20.nacos.common.ConnectionSetupRequest.LabelsEntryR\x06labels\x12Z\n" +
	"\fabilityTable\x18\x05 \x03(\v26.nacos.common.ConnectionSetupRequest.AbilityTableEntryR\fabilityTable\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11AbilityTableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xc5\x01\n" +
	"\x0fSetupAckRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12S\n" +
	"\fabilityTable\x18\x02 \x03(\v2/.nacos.common.SetupAckRequest.AbilityTableEntryR\fabilityTable\x1a?\n" +
	"\x11AbilityTableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x88\x01\n" +
	"\x10SetupAckResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x93\x01\n" +
	"\x13ConnectResetRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bserverIp\x18\x02 \x01(\tR\bserverIp\x12\x1e\n" +
	"\n" +
	"serverPort\x18\x03 \x01(\tR\n" +
	"serverPort\x12\"\n" +
	"\fconnectionId\x18\x04 \x01(\tR\fconnectionId\"2\n" +
	"\x12ServerCheckRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"\xed\x01\n" +
	"\x13ServerCheckResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\"\n" +
	"\fconnectionId\x18\x05 \x01(\tR\fconnectionId\x12<\n" +
	"\x19supportAbilityNegotiation\x18\x06 \x01(\bR\x19supportAbilityNegotiation\"2\n" +
	"\x12HealthCheckRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\"\x8b\x01\n" +
	"\x13HealthCheckResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x85\x01\n" +
	"\rErrorResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestIdB.Z,github.com/cxhello/nacos-sdk-proto/go/commonb\x06proto3"

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData []byte
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)))
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_common_common_proto_goTypes = []any{
	(*ConnectionSetupRequest)(nil), // 0: nacos.common.ConnectionSetupRequest
	(*SetupAckRequest)(nil),        // 1: nacos.common.SetupAckRequest
	(*SetupAckResponse)(nil),       // 2: nacos.common.SetupAckResponse
	(*ConnectResetRequest)(nil),    // 3: nacos.common.ConnectResetRequest
	(*ServerCheckRequest)(nil),     // 4: nacos.common.ServerCheckRequest
	(*ServerCheckResponse)(nil),    // 5: nacos.common.ServerCheckResponse
	(*HealthCheckRequest)(nil),     // 6: nacos.common.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 7: nacos.common.HealthCheckResponse
	(*ErrorResponse)(nil),          // 8: nacos.common.ErrorResponse
	nil,                            // 9: nacos.common.ConnectionSetupRequest.LabelsEntry
	nil,                            // 10: nacos.common.ConnectionSetupRequest.AbilityTableEntry
	nil,                            // 11: nacos.common.SetupAckRequest.AbilityTableEntry
}
var file_common_common_proto_depIdxs = []int32{
	9,  // 0: nacos.common.ConnectionSetupRequest.labels:type_name -> nacos.common.ConnectionSetupRequest.LabelsEntry
	10, // 1: nacos.common.ConnectionSetupRequest.abilityTable:type_name -> nacos.common.ConnectionSetupRequest.AbilityTableEntry
	11, // 2: nacos.common.SetupAckRequest.abilityTable:type_name -> nacos.common.SetupAckRequest.AbilityTableEntry
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_proto_rawDesc), len(file_common_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
