// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: config/config_request.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "ConfigQueryRequest"
type ConfigQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigQueryRequest) Reset() {
	*x = ConfigQueryRequest{}
	mi := &file_config_config_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQueryRequest) ProtoMessage() {}

func (x *ConfigQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQueryRequest.ProtoReflect.Descriptor instead.
func (*ConfigQueryRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigQueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigQueryRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigQueryRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigQueryRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigQueryRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// metadata.type = "ConfigPublishRequest"
type ConfigPublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CasMd5        string                 `protobuf:"bytes,6,opt,name=casMd5,proto3" json:"casMd5,omitempty"`
	AdditionMap   map[string]string      `protobuf:"bytes,7,rep,name=additionMap,proto3" json:"additionMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPublishRequest) Reset() {
	*x = ConfigPublishRequest{}
	mi := &file_config_config_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPublishRequest) ProtoMessage() {}

func (x *ConfigPublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPublishRequest.ProtoReflect.Descriptor instead.
func (*ConfigPublishRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigPublishRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigPublishRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigPublishRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigPublishRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigPublishRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigPublishRequest) GetCasMd5() string {
	if x != nil {
		return x.CasMd5
	}
	return ""
}

func (x *ConfigPublishRequest) GetAdditionMap() map[string]string {
	if x != nil {
		return x.AdditionMap
	}
	return nil
}

// metadata.type = "ConfigRemoveRequest"
type ConfigRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRemoveRequest) Reset() {
	*x = ConfigRemoveRequest{}
	mi := &file_config_config_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRemoveRequest) ProtoMessage() {}

func (x *ConfigRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRemoveRequest.ProtoReflect.Descriptor instead.
func (*ConfigRemoveRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigRemoveRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigRemoveRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigRemoveRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigRemoveRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigRemoveRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// metadata.type = "ConfigBatchListenRequest"
type ConfigBatchListenRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestId            string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId               string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group                string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant               string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Listen               bool                   `protobuf:"varint,5,opt,name=listen,proto3" json:"listen,omitempty"`
	ConfigListenContexts []*ConfigListenContext `protobuf:"bytes,6,rep,name=configListenContexts,proto3" json:"configListenContexts,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConfigBatchListenRequest) Reset() {
	*x = ConfigBatchListenRequest{}
	mi := &file_config_config_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigBatchListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBatchListenRequest) ProtoMessage() {}

func (x *ConfigBatchListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBatchListenRequest.ProtoReflect.Descriptor instead.
func (*ConfigBatchListenRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigBatchListenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ConfigBatchListenRequest) GetListen() bool {
	if x != nil {
		return x.Listen
	}
	return false
}

func (x *ConfigBatchListenRequest) GetConfigListenContexts() []*ConfigListenContext {
	if x != nil {
		return x.ConfigListenContexts
	}
	return nil
}

type ConfigListenContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Md5           string                 `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	DataId        string                 `protobuf:"bytes,3,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigListenContext) Reset() {
	*x = ConfigListenContext{}
	mi := &file_config_config_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigListenContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigListenContext) ProtoMessage() {}

func (x *ConfigListenContext) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigListenContext.ProtoReflect.Descriptor instead.
func (*ConfigListenContext) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigListenContext) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigListenContext) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ConfigListenContext) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigListenContext) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

// metadata.type = "ConfigChangeNotifyRequest" (server -> client)
type ConfigChangeNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Tenant        string                 `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigChangeNotifyRequest) Reset() {
	*x = ConfigChangeNotifyRequest{}
	mi := &file_config_config_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeNotifyRequest) ProtoMessage() {}

func (x *ConfigChangeNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeNotifyRequest.ProtoReflect.Descriptor instead.
func (*ConfigChangeNotifyRequest) Descriptor() ([]byte, []int) {
	return file_config_config_request_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigChangeNotifyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigChangeNotifyRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigChangeNotifyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigChangeNotifyRequest) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

var File_config_config_request_proto protoreflect.FileDescriptor

const file_config_config_request_proto_rawDesc = "" +
	"\n" +
	"\x1bconfig/config_request.proto\x12\fnacos.config\"\x8a\x01\n" +
	"\x12ConfigQueryRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\"\xc3\x02\n" +
	"\x14ConfigPublishRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06casMd5\x18\x06 \x01(\tR\x06casMd5\x12U\n" +
	"\vadditionMap\x18\a \x03(\v23.nacos.config.ConfigPublishRequest.AdditionMapEntryR\vadditionMap\x1a>\n" +
	"\x10AdditionMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\x13ConfigRemoveRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\"\xed\x01\n" +
	"\x18ConfigBatchListenRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06listen\x18\x05 \x01(\bR\x06listen\x12U\n" +
	"\x14configListenContexts\x18\x06 \x03(\v2!.nacos.config.ConfigListenContextR\x14configListenContexts\"m\n" +
	"\x13ConfigListenContext\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03md5\x18\x02 \x01(\tR\x03md5\x12\x16\n" +
	"\x06dataId\x18\x03 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenant\"\x7f\n" +
	"\x19ConfigChangeNotifyRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x16\n" +
	"\x06tenant\x18\x04 \x01(\tR\x06tenantB.Z,github.com/cxhello/nacos-sdk-proto/go/configb\x06proto3"

var (
	file_config_config_request_proto_rawDescOnce sync.Once
	file_config_config_request_proto_rawDescData []byte
)

func file_config_config_request_proto_rawDescGZIP() []byte {
	file_config_config_request_proto_rawDescOnce.Do(func() {
		file_config_config_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_config_request_proto_rawDesc), len(file_config_config_request_proto_rawDesc)))
	})
	return file_config_config_request_proto_rawDescData
}

var file_config_config_request_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_config_config_request_proto_goTypes = []any{
	(*ConfigQueryRequest)(nil),        // 0: nacos.config.ConfigQueryRequest
	(*ConfigPublishRequest)(nil),      // 1: nacos.config.ConfigPublishRequest
	(*ConfigRemoveRequest)(nil),       // 2: nacos.config.ConfigRemoveRequest
	(*ConfigBatchListenRequest)(nil),  // 3: nacos.config.ConfigBatchListenRequest
	(*ConfigListenContext)(nil),       // 4: nacos.config.ConfigListenContext
	(*ConfigChangeNotifyRequest)(nil), // 5: nacos.config.ConfigChangeNotifyRequest
	nil,                               // 6: nacos.config.ConfigPublishRequest.AdditionMapEntry
}
var file_config_config_request_proto_depIdxs = []int32{
	6, // 0: nacos.config.ConfigPublishRequest.additionMap:type_name -> nacos.config.ConfigPublishRequest.AdditionMapEntry
	4, // 1: nacos.config.ConfigBatchListenRequest.configListenContexts:type_name -> nacos.config.ConfigListenContext
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_config_request_proto_init() }
func file_config_config_request_proto_init() {
	if File_config_config_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_config_request_proto_rawDesc), len(file_config_config_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_config_request_proto_goTypes,
		DependencyIndexes: file_config_config_request_proto_depIdxs,
		MessageInfos:      file_config_config_request_proto_msgTypes,
	}.Build()
	File_config_config_request_proto = out.File
	file_config_config_request_proto_goTypes = nil
	file_config_config_request_proto_depIdxs = nil
}
