// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: config/config_response.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "ConfigQueryResponse"
type ConfigQueryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResultCode       int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode        int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId        string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Content          string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	EncryptedDataKey string                 `protobuf:"bytes,6,opt,name=encryptedDataKey,proto3" json:"encryptedDataKey,omitempty"`
	ContentType      string                 `protobuf:"bytes,7,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Md5              string                 `protobuf:"bytes,8,opt,name=md5,proto3" json:"md5,omitempty"`
	LastModified     int64                  `protobuf:"varint,9,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	IsBeta           bool                   `protobuf:"varint,10,opt,name=isBeta,proto3" json:"isBeta,omitempty"`
	Tag              string                 `protobuf:"bytes,11,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfigQueryResponse) Reset() {
	*x = ConfigQueryResponse{}
	mi := &file_config_config_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigQueryResponse) ProtoMessage() {}

func (x *ConfigQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigQueryResponse.ProtoReflect.Descriptor instead.
func (*ConfigQueryResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigQueryResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigQueryResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigQueryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigQueryResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConfigQueryResponse) GetEncryptedDataKey() string {
	if x != nil {
		return x.EncryptedDataKey
	}
	return ""
}

func (x *ConfigQueryResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ConfigQueryResponse) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ConfigQueryResponse) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *ConfigQueryResponse) GetIsBeta() bool {
	if x != nil {
		return x.IsBeta
	}
	return false
}

func (x *ConfigQueryResponse) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// metadata.type = "ConfigPublishResponse"
type ConfigPublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPublishResponse) Reset() {
	*x = ConfigPublishResponse{}
	mi := &file_config_config_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPublishResponse) ProtoMessage() {}

func (x *ConfigPublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPublishResponse.ProtoReflect.Descriptor instead.
func (*ConfigPublishResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigPublishResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigPublishResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigPublishResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigPublishResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigRemoveResponse"
type ConfigRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRemoveResponse) Reset() {
	*x = ConfigRemoveResponse{}
	mi := &file_config_config_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRemoveResponse) ProtoMessage() {}

func (x *ConfigRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRemoveResponse.ProtoReflect.Descriptor instead.
func (*ConfigRemoveResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigRemoveResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigRemoveResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigRemoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigRemoveResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// metadata.type = "ConfigChangeBatchListenResponse"
// NOTE: Java class name is ConfigChangeBatchListenResponse (NOT ConfigBatchListenResponse)
type ConfigChangeBatchListenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultCode     int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode      int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId      string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ChangedConfigs []*ConfigContext       `protobuf:"bytes,5,rep,name=changedConfigs,proto3" json:"changedConfigs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigChangeBatchListenResponse) Reset() {
	*x = ConfigChangeBatchListenResponse{}
	mi := &file_config_config_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigChangeBatchListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChangeBatchListenResponse) ProtoMessage() {}

func (x *ConfigChangeBatchListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChangeBatchListenResponse.ProtoReflect.Descriptor instead.
func (*ConfigChangeBatchListenResponse) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigChangeBatchListenResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *ConfigChangeBatchListenResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ConfigChangeBatchListenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfigChangeBatchListenResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ConfigChangeBatchListenResponse) GetChangedConfigs() []*ConfigContext {
	if x != nil {
		return x.ChangedConfigs
	}
	return nil
}

type ConfigContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	DataId        string                 `protobuf:"bytes,2,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Tenant        string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigContext) Reset() {
	*x = ConfigContext{}
	mi := &file_config_config_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigContext) ProtoMessage() {}

func (x *ConfigContext) ProtoReflect() protoreflect.Message {
	mi := &file_config_config_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigContext.ProtoReflect.Descriptor instead.
func (*ConfigContext) Descriptor() ([]byte, []int) {
	return file_config_config_response_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigContext) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigContext) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *ConfigContext) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

var File_config_config_response_proto protoreflect.FileDescriptor

const file_config_config_response_proto_rawDesc = "" +
	"\n" +
	"\x1cconfig/config_response.proto\x12\fnacos.config\"\xd3\x02\n" +
	"\x13ConfigQueryResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12*\n" +
	"\x10encryptedDataKey\x18\x06 \x01(\tR\x10encryptedDataKey\x12 \n" +
	"\vcontentType\x18\a \x01(\tR\vcontentType\x12\x10\n" +
	"\x03md5\x18\b \x01(\tR\x03md5\x12\"\n" +
	"\flastModified\x18\t \x01(\x03R\flastModified\x12\x16\n" +
	"\x06isBeta\x18\n" +
	" \x01(\bR\x06isBeta\x12\x10\n" +
	"\x03tag\x18\v \x01(\tR\x03tag\"\x8d\x01\n" +
	"\x15ConfigPublishResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\x8c\x01\n" +
	"\x14ConfigRemoveResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\"\xdc\x01\n" +
	"\x1fConfigChangeBatchListenResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12C\n" +
	"\x0echangedConfigs\x18\x05 \x03(\v2\x1b.nacos.config.ConfigContextR\x0echangedConfigs\"U\n" +
	"\rConfigContext\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x16\n" +
	"\x06dataId\x18\x02 \x01(\tR\x06dataId\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenantB.Z,github.com/cxhello/nacos-sdk-proto/go/configb\x06proto3"

var (
	file_config_config_response_proto_rawDescOnce sync.Once
	file_config_config_response_proto_rawDescData []byte
)

func file_config_config_response_proto_rawDescGZIP() []byte {
	file_config_config_response_proto_rawDescOnce.Do(func() {
		file_config_config_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_config_response_proto_rawDesc), len(file_config_config_response_proto_rawDesc)))
	})
	return file_config_config_response_proto_rawDescData
}

var file_config_config_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_config_response_proto_goTypes = []any{
	(*ConfigQueryResponse)(nil),             // 0: nacos.config.ConfigQueryResponse
	(*ConfigPublishResponse)(nil),           // 1: nacos.config.ConfigPublishResponse
	(*ConfigRemoveResponse)(nil),            // 2: nacos.config.ConfigRemoveResponse
	(*ConfigChangeBatchListenResponse)(nil), // 3: nacos.config.ConfigChangeBatchListenResponse
	(*ConfigContext)(nil),                   // 4: nacos.config.ConfigContext
}
var file_config_config_response_proto_depIdxs = []int32{
	4, // 0: nacos.config.ConfigChangeBatchListenResponse.changedConfigs:type_name -> nacos.config.ConfigContext
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_config_response_proto_init() }
func file_config_config_response_proto_init() {
	if File_config_config_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_config_response_proto_rawDesc), len(file_config_config_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_config_response_proto_goTypes,
		DependencyIndexes: file_config_config_response_proto_depIdxs,
		MessageInfos:      file_config_config_response_proto_msgTypes,
	}.Build()
	File_config_config_response_proto = out.File
	file_config_config_response_proto_goTypes = nil
	file_config_config_response_proto_depIdxs = nil
}
