// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: naming/naming_request.proto

package naming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "InstanceRequest"
type InstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Instance      *Instance              `protobuf:"bytes,6,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRequest) Reset() {
	*x = InstanceRequest{}
	mi := &file_naming_naming_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRequest) ProtoMessage() {}

func (x *InstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRequest.ProtoReflect.Descriptor instead.
func (*InstanceRequest) Descriptor() ([]byte, []int) {
	return file_naming_naming_request_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InstanceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InstanceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *InstanceRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *InstanceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InstanceRequest) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// metadata.type = "SubscribeServiceRequest"
type SubscribeServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Subscribe     bool                   `protobuf:"varint,5,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	Clusters      string                 `protobuf:"bytes,6,opt,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServiceRequest) Reset() {
	*x = SubscribeServiceRequest{}
	mi := &file_naming_naming_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServiceRequest) ProtoMessage() {}

func (x *SubscribeServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServiceRequest.ProtoReflect.Descriptor instead.
func (*SubscribeServiceRequest) Descriptor() ([]byte, []int) {
	return file_naming_naming_request_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeServiceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeServiceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubscribeServiceRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SubscribeServiceRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *SubscribeServiceRequest) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *SubscribeServiceRequest) GetClusters() string {
	if x != nil {
		return x.Clusters
	}
	return ""
}

// metadata.type = "ServiceQueryRequest"
type ServiceQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Cluster       string                 `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	HealthyOnly   bool                   `protobuf:"varint,6,opt,name=healthyOnly,proto3" json:"healthyOnly,omitempty"`
	UdpPort       int32                  `protobuf:"varint,7,opt,name=udpPort,proto3" json:"udpPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceQueryRequest) Reset() {
	*x = ServiceQueryRequest{}
	mi := &file_naming_naming_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceQueryRequest) ProtoMessage() {}

func (x *ServiceQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceQueryRequest.ProtoReflect.Descriptor instead.
func (*ServiceQueryRequest) Descriptor() ([]byte, []int) {
	return file_naming_naming_request_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceQueryRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceQueryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceQueryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceQueryRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ServiceQueryRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ServiceQueryRequest) GetHealthyOnly() bool {
	if x != nil {
		return x.HealthyOnly
	}
	return false
}

func (x *ServiceQueryRequest) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

var File_naming_naming_request_proto protoreflect.FileDescriptor

const file_naming_naming_request_proto_rawDesc = "" +
	"\n" +
	"\x1bnaming/naming_request.proto\x12\fnacos.naming\x1a\x15naming/instance.proto\"\xd5\x01\n" +
	"\x0fInstanceRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x122\n" +
	"\binstance\x18\x06 \x01(\v2\x16.nacos.naming.InstanceR\binstance\"\xcf\x01\n" +
	"\x17SubscribeServiceRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12\x1c\n" +
	"\tsubscribe\x18\x05 \x01(\bR\tsubscribe\x12\x1a\n" +
	"\bclusters\x18\x06 \x01(\tR\bclusters\"\xe7\x01\n" +
	"\x13ServiceQueryRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12 \n" +
	"\vserviceName\x18\x03 \x01(\tR\vserviceName\x12\x1c\n" +
	"\tgroupName\x18\x04 \x01(\tR\tgroupName\x12\x18\n" +
	"\acluster\x18\x05 \x01(\tR\acluster\x12 \n" +
	"\vhealthyOnly\x18\x06 \x01(\bR\vhealthyOnly\x12\x18\n" +
	"\audpPort\x18\a \x01(\x05R\audpPortB.Z,github.com/cxhello/nacos-sdk-proto/go/namingb\x06proto3"

var (
	file_naming_naming_request_proto_rawDescOnce sync.Once
	file_naming_naming_request_proto_rawDescData []byte
)

func file_naming_naming_request_proto_rawDescGZIP() []byte {
	file_naming_naming_request_proto_rawDescOnce.Do(func() {
		file_naming_naming_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_naming_naming_request_proto_rawDesc), len(file_naming_naming_request_proto_rawDesc)))
	})
	return file_naming_naming_request_proto_rawDescData
}

var file_naming_naming_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_naming_naming_request_proto_goTypes = []any{
	(*InstanceRequest)(nil),         // 0: nacos.naming.InstanceRequest
	(*SubscribeServiceRequest)(nil), // 1: nacos.naming.SubscribeServiceRequest
	(*ServiceQueryRequest)(nil),     // 2: nacos.naming.ServiceQueryRequest
	(*Instance)(nil),                // 3: nacos.naming.Instance
}
var file_naming_naming_request_proto_depIdxs = []int32{
	3, // 0: nacos.naming.InstanceRequest.instance:type_name -> nacos.naming.Instance
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_naming_naming_request_proto_init() }
func file_naming_naming_request_proto_init() {
	if File_naming_naming_request_proto != nil {
		return
	}
	file_naming_instance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_naming_naming_request_proto_rawDesc), len(file_naming_naming_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_naming_naming_request_proto_goTypes,
		DependencyIndexes: file_naming_naming_request_proto_depIdxs,
		MessageInfos:      file_naming_naming_request_proto_msgTypes,
	}.Build()
	File_naming_naming_request_proto = out.File
	file_naming_naming_request_proto_goTypes = nil
	file_naming_naming_request_proto_depIdxs = nil
}
