// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: naming/naming_response.proto

package naming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata.type = "InstanceResponse"
type InstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceResponse) Reset() {
	*x = InstanceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceResponse) ProtoMessage() {}

func (x *InstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceResponse.ProtoReflect.Descriptor instead.
func (*InstanceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *InstanceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *InstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstanceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InstanceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// metadata.type = "SubscribeServiceResponse"
type SubscribeServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,5,opt,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeServiceResponse) Reset() {
	*x = SubscribeServiceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeServiceResponse) ProtoMessage() {}

func (x *SubscribeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeServiceResponse.ProtoReflect.Descriptor instead.
func (*SubscribeServiceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeServiceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SubscribeServiceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SubscribeServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SubscribeServiceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeServiceResponse) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

// metadata.type = "QueryServiceResponse"
// NOTE: Java class name is QueryServiceResponse (NOT ServiceQueryResponse)
type QueryServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultCode    int32                  `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	ServiceInfo   *ServiceInfo           `protobuf:"bytes,5,opt,name=serviceInfo,proto3" json:"serviceInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryServiceResponse) Reset() {
	*x = QueryServiceResponse{}
	mi := &file_naming_naming_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServiceResponse) ProtoMessage() {}

func (x *QueryServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_naming_naming_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServiceResponse.ProtoReflect.Descriptor instead.
func (*QueryServiceResponse) Descriptor() ([]byte, []int) {
	return file_naming_naming_response_proto_rawDescGZIP(), []int{2}
}

func (x *QueryServiceResponse) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *QueryServiceResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *QueryServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryServiceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryServiceResponse) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

var File_naming_naming_response_proto protoreflect.FileDescriptor

const file_naming_naming_response_proto_rawDesc = "" +
	"\n" +
	"\x1cnaming/naming_response.proto\x12\fnacos.naming\x1a\x15naming/instance.proto\"\x9c\x01\n" +
	"\x10InstanceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\xcd\x01\n" +
	"\x18SubscribeServiceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12;\n" +
	"\vserviceInfo\x18\x05 \x01(\v2\x19.nacos.naming.ServiceInfoR\vserviceInfo\"\xc9\x01\n" +
	"\x14QueryServiceResponse\x12\x1e\n" +
	"\n" +
	"resultCode\x18\x01 \x01(\x05R\n" +
	"resultCode\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\trequestId\x18\x04 \x01(\tR\trequestId\x12;\n" +
	"\vserviceInfo\x18\x05 \x01(\v2\x19.nacos.naming.ServiceInfoR\vserviceInfoB.Z,github.com/cxhello/nacos-sdk-proto/go/namingb\x06proto3"

var (
	file_naming_naming_response_proto_rawDescOnce sync.Once
	file_naming_naming_response_proto_rawDescData []byte
)

func file_naming_naming_response_proto_rawDescGZIP() []byte {
	file_naming_naming_response_proto_rawDescOnce.Do(func() {
		file_naming_naming_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_naming_naming_response_proto_rawDesc), len(file_naming_naming_response_proto_rawDesc)))
	})
	return file_naming_naming_response_proto_rawDescData
}

var file_naming_naming_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_naming_naming_response_proto_goTypes = []any{
	(*InstanceResponse)(nil),         // 0: nacos.naming.InstanceResponse
	(*SubscribeServiceResponse)(nil), // 1: nacos.naming.SubscribeServiceResponse
	(*QueryServiceResponse)(nil),     // 2: nacos.naming.QueryServiceResponse
	(*ServiceInfo)(nil),              // 3: nacos.naming.ServiceInfo
}
var file_naming_naming_response_proto_depIdxs = []int32{
	3, // 0: nacos.naming.SubscribeServiceResponse.serviceInfo:type_name -> nacos.naming.ServiceInfo
	3, // 1: nacos.naming.QueryServiceResponse.serviceInfo:type_name -> nacos.naming.ServiceInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_naming_naming_response_proto_init() }
func file_naming_naming_response_proto_init() {
	if File_naming_naming_response_proto != nil {
		return
	}
	file_naming_instance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_naming_naming_response_proto_rawDesc), len(file_naming_naming_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_naming_naming_response_proto_goTypes,
		DependencyIndexes: file_naming_naming_response_proto_depIdxs,
		MessageInfos:      file_naming_naming_response_proto_msgTypes,
	}.Build()
	File_naming_naming_response_proto = out.File
	file_naming_naming_response_proto_goTypes = nil
	file_naming_naming_response_proto_depIdxs = nil
}
